# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO
# WHERE ITEM_ID not in (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID is NOT NULL)
# ORDER BY 1 DESC;

# not exist?
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO INFO
WHERE NOT EXISTS (SELECT 1  FROM ITEM_TREE TREE WHERE TREE.PARENT_ITEM_ID = INFO.ITEM_ID)
ORDER BY ITEM_ID DESC