SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1,' ', STREET_ADDRESS2) as 전체주소, CONCAT(LEFT(TLNO, 3),'-', MID(TLNO, 4, 4),'-', RIGHT(TLNO,4)) as 전화번호
FROM USED_GOODS_BOARD
LEFT JOIN USED_GOODS_USER 
ON WRITER_ID = USER_ID
GROUP BY USER_ID
HAVING COUNT(USER_ID) >= 3
ORDER BY USER_ID DESC;