SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) as MONTH, u.GENDER, COUNT(DISTINCT o.USER_ID) as USERS
FROM USER_INFO as u
JOIN ONLINE_SALE as o
ON u.USER_ID = o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1,2,3;