WITH CAR as (
            SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 as DURATION,
            CASE
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                END as DURATION_TYPE
            FROM CAR_RENTAL_COMPANY_CAR c
            JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
            ON c.CAR_ID = h.CAR_ID
            WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, CASE
                        WHEN ca.DURATION_TYPE = '7일 이상' THEN ROUND(DAILY_FEE * (1- DISCOUNT_RATE/100) * DURATION, 0)
                        WHEN ca.DURATION_TYPE = '30일 이상' THEN ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * DURATION, 0)
                        WHEN ca.DURATION_TYPE = '90일 이상' THEN ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * DURATION, 0)
                        ELSE ROUND(DAILY_FEE * DURATION, 0)
                        END AS FEE
FROM CAR ca
LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭') p
ON ca.DURATION_TYPE = p.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;