WITH AP as (SELECT APNT_YMD, APNT_NO, PT_NO, a.MCDP_CD, MDDR_ID ,DR_NAME, APNT_CNCL_YN, APNT_CNCL_YMD 
FROM APPOINTMENT a
JOIN DOCTOR d
ON MDDR_ID = DR_ID
WHERE a.MCDP_CD = 'CS'
)
SELECT APNT_NO, PT_NAME, ap.PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM AP ap
JOIN PATIENT p
ON ap.PT_NO = p.PT_NO
WHERE APNT_YMD Like '%2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;
