WITH BOOK_TOTAL_SALE as (
SELECT b.AUTHOR_ID, b.CATEGORY, SUM(b.PRICE *  s.SALES) as TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY b.AUTHOR_ID, b.CATEGORY
)

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, bs.CATEGORY, bs.TOTAL_SALES
FROM BOOK_TOTAL_SALE as bs
JOIN AUTHOR as a
ON bs.AUTHOR_ID = a.AUTHOR_ID
ORDER BY bs.AUTHOR_ID, bs.CATEGORY DESC;
