WITH CODES AS(SELECT
             (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') as PYCODE,
              (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') as C_CODE,
              (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') as FECODE
             )

SELECT CASE
    WHEN (SKILL_CODE & FECODE) AND (SKILL_CODE & PYCODE) THEN 'A'
    WHEN (SKILL_CODE & C_CODE) THEN 'B'
    WHEN (SKILL_CODE & FECODE) THEN 'C'
        END AS GRADE, ID, EMAIL
FROM DEVELOPERS, CODES
WHERE SKILL_CODE & (FECODE + C_CODE)
ORDER BY 1, 2;
